DebugMode=0
;河南联通环境
#HomePage=http://61.158.252.149:8086/iptvepg/datasource/mobilelogin.jsp
;Summit演示环境
#HomePage=http://120.210.211.75:5080/iptvepg/datasource/mobilelogin.jsp
;展厅环境
#HomePage=http://221.226.0.75:8086/iptvepg/datasource/mobilelogin.jsp
;上海展环境
#HomePage=http://10.30.61.102:8086/iptvepg/datasource/mobilelogin.jsp
;展厅环境
#HomePage=http://221.226.0.67:8080/iptvepg/datasource/mobilelogin.jsp
;全时多屏环境
#HomePage=http://10.47.223.71:8086/iptvepg/datasource/mobilelogin.jsp
;江苏电信环境
#HomePage=http://61.160.184.55:8298/mobileAuth
;山东联通
#HomePage=http://119.164.56.210:8086/iptvepg/datasource/mobilelogin.jsp
;众测平台
#HomePage=http://158.158.80.31:8086/iptvepg/datasource/mobilelogin.jsp
#安徽移动
#HomePage=http://mappacc.ahydnet.com:5080/iptvepg/datasource/mobilelogin.jsp
#HomePage=https://ajeas.black.co.za/iptvepg/datasource/mobilelogin.jsp
#HomePage=http://172.20.2.25:8086/iptvepg/datasource/mobilelogin.jsp
#大视频3.0环境
#HomePage=http://10.47.202.182:8086/iptvepg/datasource/mobilelogin.jsp
#浙江联通
#HomePage=http://124.90.44.39:8080/iptvepg/datasource/mobilelogin.jsp
#联调环境
#HomePage=http://10.47.222.48:8086/iptvepg/datasource/mobilelogin.jsp
#用户密码 xjstest001/1
#注意手机的dns需要设置为10.47.212.123 （可以在手机上ping这个dns地址测试网络，在手机浏览器上请求登录域名测试dns是否正确配置）
#HomePage=https://black.co.za:8443/iptvepg/datasource/mobilelogin.jsp
#AT现网环境
#HomePage=https://iptv.at.dz:8443/iptvepg/datasource/mobilelogin.jsp
#BE现网环境
HomePage=https://tv.zala.by:443/iptvepg/datasource/mobilelogin.jsp
#展厅环境
#HomePage=http://221.226.0.75:8086/iptvepg/datasource/mobilelogin.jsp
#支付宝登陆验证环境
#HomePage=http://221.226.0.75:18086/iptvepg/datasource/mobilelogin.jsp
;Divitel版本环境
#HomePage=http://185.15.249.227:8086/iptvepg/datasource/mobilelogin.jsp
;备用EAS地址
HomePageBak=https://slaveeas.tv.zala.by:443/iptvepg/datasource/mobilelogin.jsp
UpgradeServerIpPort=http://82.209.237.253/upgrade/mobile/be_upgradeinfo_aphone.json

UpgradeResourceServer=https://tv.zala.by:8443/upgrade/mobile/resourceUpdate.json
GuestName=guestphone
GuestPassword=1
RegisterServerIpPort=202.147.196.118:80
WeChatAppKey=wx25d71c5a3be23ff5
WeChatAppSecret=3fc0cad3853b5e9c5969cbc290bb95b1
WeChatRedirectURL=http://www.zte.com.cn
WeiboShareAppKey=521969048
WeiboShareAppSecret=30a67cd032490a8b370b4badf0258a39
WeiboShareRedirectURL=http://www.weseejoy.com
QQShareAppKey=1105694965
QQShareAppSecret=mhXQ95wChoYmzJTx
DownloadModuleSwith=off
DownloadMinimumSpace=100
AllowGuestDownload=false
DownloadProxyLogLevel=2
DemoVersion=0
LoginMode=
;1为只扫zte的盒子，0为扫描全部的盒子
DlnaDevFlag=1
;5为通过CP查询的绑定列表，2为通过接口机查询账户所有  的绑定列表
DlnaOPFlag=2
APP_Market_URL=http://202.102.41.225/share_jiangsu/interface/
APP_Market_Access_Token=847CC1EF-98EB-4555-AB37-2756CE8BCEB4
Android_APPID=78864
APP_Market_Channel_Uid=12345
;是否启动DLNA，0为不启用，1为启用
DlnaFlag=1
TransactionSp=91000001
;是否启用分设，0是合设，1是分设
IsDividePlat=0
MessegePushSwitch=0
SeriesQueryByPage=1
isJiangSuHC100=0
Log_Server_Address=180.100.1.109:8181
ColumnSort_Server=10.47.222.5:9491
ColumnSort_control=0
;是否支持支付宝支付 1支持,0不支持
SupportAliPay=0
;是否支持RCS群聊 1支持,0不支持
SupportRCSGroupChat=0
;是否进行重定向
IsNeedRedirect=0
;是否用旧书签（合设）接口
UseOldBookmark=1
;是否展示山东版本内容 1是，0否
IsShanDongVersion=0
;使用自动放装
EnableTask60=0
;是否使用游客账号登陆
GuestEnable=1
;sdk日志写
Start_Debug=0
;sdk日志停止写
Stop_Debug=1
;sdk日志上传
Upload_Log=0
;是否隐藏登出 1不隐藏，0隐藏
EnableLogout=1
; 是否支持我的订购 1支持, 0不支持
SupportMySubscription=1
;是否展示安徽移动版本内容 1是，0否
IsAnHuiVersion=0
;是否支持微博分享 1支持, 0不支持
SupportWeiboShare=0
;是否支持QQ分享 1支持, 0不支持
SupportQQShare=0
;是否支持QQ空间分享 1支持, 0不支持
SupportQZoneShare=0
;是否支持FaceBook分享 1支持, 0不支持
SupportFaceBook=1
;是否展示安徽移动OTT绑定账户切图
IS_SHOW_OTT_IMG=1
;是否展示 超声波 控制开关 1展示 0不展示
IsShowVoicePrintSwitch=0
;是否展示遥控器页面 1展示 0不展示
IsShowMyRemoteCtrl=1
;是否展示帮助反馈页面 1展示 0不展示
IsShowMyHelpBack=1
;录制功能开关 1打开 0关闭
IsShowRecordSwitch=1
;是否展示启动画面引导页 1展示 0不展示
IsShowTourPage=0
;是否展示RCS聊天页面
IsShowRcsCommunication=0
;搜索类型 1为中文搜索 0为全模糊搜索
SearchType_Chinese=0
;是否支持应用汇  1是，0否
SupportAppCenter=0
;是否支持绑定帐号 1是，0否
SupportBindAccount=1
;是否支持用户账户信息 1是，0否
SupportPersonDetailInfo=1
;标题栏是否显示遥控器图标 1是，0否
IsShowRemoteIcon=1
;标题栏是否显示扫描图标 1是，0否
IsShowScanIcon=0
;标题栏显示编辑图标还是文本 1显示图标，0显示文本
IsShowEditIconOrText=0
;是否支持HC100远程下载 1是 0否
SupportRemoteDownload=0
;是否显示SmartHome版本启动页 1是 0否
IsSmartHomeStartPage=0
;是否展示童锁页面 1展示 0不展示
IsShowChildLock=1
;是否可选择展示blockTitle 1展示 0不展示
IsShowBlockTitle=0
;是否展示个性化中心页面 1展示 0不展示
IsShowCustomCenter=0
;是否支持投屏页面 1支持 0不支持
IsSupportCastScreen=1
;是否支持家庭杂志 1支持 0不支持
SupportHomeMagazine=0
;支持的预约提醒类型,4位二进制表示法，低位开始，最低位（第0位）表示本地直播提醒，次低位（第1位）表示vod预约
;次低位（第2位）表示服务器直播提醒，最高位（第3位）表示订阅
;1表示打开，0表示关闭，原则上不允许第0位与第2位同时为1
SupportOrderReminderType=0
;侧边栏需展示的标签项 以逗号分割(若不显示侧边栏则展示在‘我的’页面)
;账户侧边栏标签项
MenuTabs=REMOTER,PARENTAL,CHANNELLINEUP,SETTING,BINDING,HELP,SHARE
;My栏标签项
MY_MenuTabs=RECORDING,FAVORITE,BOOKMARK,BALANCE,PPV,PACKAGE,ORDER
;首页底部需展示的标签项 以逗号分割
BottomTabs=HOME,TV,VOD,MY,MINE
;首页儿童模式下底部需展示的标签项 以逗号分割
BottomChildTabs=RETURN,TV_CHILD,VOD_CHILD,QUIZ_CHILD,WATCHHISTORY_CHILD
;首页儿童模式下底部需展示的标签项 以逗号分割,不含QUIZ_CHILD
BottomChildTabs_NOQUIZ=RETURN,TV_CHILD,VOD_CHILD,WATCHHISTORY_CHILD
;是否隐藏QUIZ_CHILD,1隐藏,0不隐藏
IsHideQuizChild=1
;是否支持GoogleCast,1支持,0不支持
EnableGoogleCast=0
;是否隐藏侧边栏,1隐藏,0不隐藏
HideSlideMenu=1
;是否支持悬浮窗口播放 1支持 0不支持
SupportFloatingPlay=0
;播放窗口中悬浮按钮是否显示 1显示 0不显示
ShowFloatingPlayBtn=0
;是否展示片花按钮 0不展示 1展示
IsShowTrailer=1
;是否支持豆瓣评分 0不支持 1支持
IsShowDoubanRating=0
;是否支持推荐理由 0不支持 1支持
IsShowRecommendReason=0
;首页标题按钮，以逗号隔开
HomeTabs=REMOTE,SHORTCUT
;直播标题按钮，以逗号隔开
TVTabs=REMOTE,TVSWITCH
;影视标题标题按钮，以逗号隔开
VODTabs=REMOTE
;我的标题按钮，以逗号隔开
MineTabs=REMOTE,SEARCH
;发现标题按钮，以逗号隔开
DiscoverTabs=REMOTE,SEARCH
;是否支持远程消息 0不支持 1支持
IsSupportRemoteMessage=0
;是否支持连续剧扩展的甩屏接口
IsSupportSeriesDLNAExtend=1
;是否展示遥控器手势滑动控制上下左右，1展示 0不展示
IsShowRemoteGesture=0
;安徽移动统一认证SDK初始化密码
SOURCEID=131008
;安徽移动统一认证登录SDK使用的应用秘钥
APP_ID=13100803
APP_KEY=418D702F1A8A186C
;是否支持机顶盒侧收藏列表，1展示 0不展示
IsSupportSTBFavorite=0
;是否支持遥控器播控页面，1展示 0不展示
IsSupportRemotePlayControl=0
;是否强制展示启动画面引导页 1展示 0不展示（需要替换新的引导页时，需要修改为1；与上一个版本相比未变更引导页时，修改为0）
IsForceShowTourPage=1
;是否支持支付宝授权登录 1支持 其他不支持
IsSupportAliAuthLogin=0
;是否支持新片预约
IsSupportOnlineSubscribe=0
;是否支持社区评论
IsSupportComment=0
;是否支持下载渠道统计、使用时长统计、家庭杂志查看次数统计
IsSupportDataStatistics=0
;是否支持头像功能  1是 0不是
IsOpenHeadFunction=0
;是否支持用户修改密码 1支持 0不支持
IsSupportChangePassword=1
;是否支持评分 1支持，0不支持
IsSupportMark=1
;影视评分功能 1表示默认取详情接口返回的starlevel字段 0表示通过计算得出来的评分
IsShowDefaultRatingFunction=0
;是否支持换肤功能（包括我的页面换肤入口是否展示） 1支持 0不支持
IsSupportSwitchSkin=0
;是否展示精彩页面的家庭杂志、我的播单入口
IsSupportMagazineAndPlayList=0
;是否支持多窗口播放 1支持 0不支持
SupportMultiWindowPlay=0
;短信登录 1:短信登陆 0：账号密码登陆
Msg_login=1
;是否只支持EPG平台订购 1是 0不是
IsOnlySupportEPGPayment=1
;是否禁用VIP功能 1禁用 0不禁用
ForbiddenVIPFunction=
;是否禁用多屏同看 1禁止 0不禁用
ForbiddenMulScreenPlay=1
;是否禁用自注册功能 1禁用 0不禁用
ForbiddenRegisterFunction=0
;是否是兴云TV的订购流程 1使用 0不用
UseXingTVOrder=0
;星云视频定制 是否集成百度语音  1支持 0不支持
IsBaiduVoice=1
;是否支持首页PCT编排展示 0默认不支持
IsSupportPCT=0
;是否跳过片头片尾 1跳过 0不跳过
IsSkipDuration=0
;blackout 控制
BlackOut_Control=0
;blackout cp 服务器地址
BlackOut_Server = 10.47.202.181:9074
;星云视频定制 是否展示内容观看等级提示 1展示 0不展示
IsShowContentRank=0
;是否支持首页HomeTrendingNow展示 0默认不支持
IsSupportTrendingNow=0
;是否展示产品包页面 1展示 0不展示
IsShowProduct=1
;星云视频定制 是否展示TV观看记录 1展示 0不展示
IsTVHistory=0
;是否禁用欧美版本的登录功能 1禁用 0不禁用
EuropeLogin=1
;是否支持隐藏搜索VOD
IsSupportHideSearchVOD=0
;是否开启播放并发控制
IsSupportConcurrencyControl=1
;是否展示今日看单
IsSupportToDayPrevue=1
;是否展示订购锁页面 1展示 0不展示
IsShowOrderLock=0
;是否支持cast功能 1支持 0不支持 欧美版本定制功能
Is_Use_Cast_Flag=0
;是否支持个性化标签 1支持 0不支持
Is_Show_Individuality_Label=0
;是否开启Recent功能 1是 0不是
isOpenRencent=0
;是否开启扫码登录功能 1是 0不是
isOpenLoginScan=0
;是否开启查询终端绑定功能 1是 0不是
isOpenTerminalBinding=1
;是否通用版本 1是 0不是
isGeneralVersion=0
;我的页面是否展示分享条目 1展示 0不展示
isShowAppShareItem=1
;我的页面是否展示收藏条目 1展示 0不展示
isShowFavoriteItem=1
;我的页面是否展示消息条目 1展示 0不展示
isShowMsgItem=0
;我的页面是否展示下载条目 1展示 0不展示
isShowDownloadItem=0
;我的页面是否展示CloudDVR条目 1展示 0不展示
isShowRecordingItem=1
;我的页面是否展示电视预约条目 1展示 0不展示
Reminders=1
;我的页面是否展示Feature条目 1展示 0不展示
isShowFeatureItem=0
;blackout功能开关 1开启 0关闭
isBlackout=1
;是否显示tvod分享按钮 1显示 0关闭
isShareBtn=1
;是否显示直播栏目排序及频道排序 1显示 0关闭
isShowTvColumnSort=0
;是否启用StartOver功能 1开启 0关闭
isStartOver=0
;已订购 为订购是否展示 1展示 0不展示
isShowSub=0
;是否是加拿大版本 1不是 0是
isAltima=1
;我的页面是否支持上滑展示用户名布局标题栏 1支持 0不支持
isSupportUserTop=1
;是否是阿尔及利亚版本 1是 0不是
isAt=0
;是否是通用版本 1是 0不是
isShow=1
;是否是安徽移动版本 1是 0不是
isAnHui=0
;录制的类型 1: Npvr  其余默认CloudDvr
isNPVR=1
;是否支持VOD中插广告 1支持 0不支持
isSupportVodMiddleAds=1
;是否支持查询插广告 1支持 0不支持
isSupportQueryAds=1
;是否展示在线订购页面 1是 0不是
isShowRecharge=1
;是否展示启动广告页面 1是 0不是
isShowSplashAD=0
;是否展示PPV页面 1是 0不是
isPPV=1
;是否节目单限制时移
isTsTvEnable=1
;是否禁用我的账户页面1禁用 0不禁用
isShowAccount=1
;筛选是否展示免费条目 1展示 0不展示
isShowFree=1
;是否展示资源模板中的级别图标 1展示 0不展示
isShowImgLevel=0
;ini文件版本号
VersionCode=2
;genre锁,是否根据genreidlist字段来判断 1是 0不是
isGenreLockByGenreIdList=1

