[softda]
p-cscf=10.47.223.168
IMSSSPort=5060
IMSDomain=10.47.223.168
UserName=sip:88880005@10.47.223.168
UserAuthPassword=1234
UserAuthId=
H264_VidSize=AUTO
CpServerAddr=61.132.54.29
CpHttpPort=8081
CpHttpSSLPort=443
Msisdn=1
PromptToken=2
VedioDeviceNo=1
IsNeedP2P=1
VideoConfAsUri=sip:32@mmconf100.ucs.com.cn
VideoConfDomainName=mmconf100.ucs.com.cn
NabServerAddr = 10.47.178.91
NabServerPort = 8800
NabIconPath = /storage/sdcard0/com.zte.ztercs/nab/
CapablityList=
SDKLogLevel=1


[SIP_CFG]
HasUserPhone=1


[ZIME_CONFIG]
;=0 Android; =1 NV; =3 MTK ;=5 Amlogic
PlatformType=0
EnableCodecSet=1
;10000-debug 50000-error
LogLevel=40000
VQE_SCENE=0
bVBREnable=1
InitialBitRate=512000
s32BitRate=1500000
MaxBitRate=1500000
FrameRate=20
IframeInterval=2000
VidSize=1
bQoS=0
b32AEC=1
b32NS=1
ZimeLogPath=/sdcard

[MSG_CFG]
GroupChatServAddr=sip:1250100100@rcsgroup.zte.com.cn
AttachFilePath=/storage/sdcard0/com.zte.ztercs/file/receive/
